### ISSUE TITLE
consider adding remarks or descriptions

### ISSUE THREAD

**Issue by eduarddrenth** [annotation/stam#3]
Especially with annotationdataset and annotationdata it may be a good idea to add a clarifying remark.

**Comment by proycon** [comment]
Where do you mean exactly? Each is currently described in the text in its own section (https://github.com/annotation/stam/blob/master/README.md#class-annotation-data-set, https://github.com/annotation/stam/blob/master/README.md#class-annotationdata).

In the UML schema there should also be a short description for each.

**Comment by eduarddrenth** [comment]
Ik bedoel dat in het datamodel (UML) eem remark opgenomen kan worden zodat stam gebruikers hun datasets en data kunnen beschrijven (bijvoorbeeld link naar vocabulaire of iest anders)

**Comment by proycon** [comment]
Ah, je bedoelt iets als een remark/description veld op die klassen; metadata dus?  Dat kan al in het huidige model ook al prima. Metadata is namelijk gewoon annotatie. In het geval dat je schetst zou je een Annotation kunnen heb met een DataSetSelector, en een DataKey "remark" of "description" of (voor compatibiliteit met RDF) iets formeels als https://schema.org/description  ofzo (STAM definieert zo goed als geen eigen vocabulaire verder)

**Comment by eduarddrenth** [comment]
ok, isn't that a bit complex (overgeneralized) for just a description?

**Comment by eduarddrenth** [comment]
More problematic I think is that with this construct an annotation becomes unclear. On the one hand it is meant to describe external data while on the other it is used to describe the internal model. I would avoid this kind of ambiguity.

**Comment by dirkroorda** [comment]
I find this a bit difficult to follow. 
On the one hand, there is the STAM proposal. It is a data model, and the model has several elements and relationships between them. If these elements need descriptions or comments, that can be done in a narrative, or in whatever way people see fit. But not by means of annotations in the STAM sense, I think, because the STAM model is not a dataset itself.

Unless @proycon really wants to do the Gödel trick: represent STAM as a STAM dataset. But I think that is an academic exercise.

At an other level, you may have a dataset and annotation sets with it all in the STAM model. If some of those data or annotations need explanations, you can add them in the form of STAM annotations. If an annotation set as a whole needs a explanation, I'm not sure whether that is also an annotation, or metadata of the annotation set.

**Comment by proycon** [comment]
> ok, isn't that a bit complex (overgeneralized) for just a description?

It is quite generalized, but STAM is deliberately set up to define a minimum of constructs to model all kinds of annotation, whilst being completely agnostic to the vocabulary or paradigm one uses for annotation (that's up to the user). Anyone using STAM will always need some layer on top of that defines the vocabulary (the AnnotationDataSet).

> More problematic I think is that with this construct an annotation becomes unclear. On the one hand it is meant to describe external data while on the other it is used to describe the internal model. I would avoid this kind of ambiguity.

That's an interesting point, I do see the concern, but I think in real use-cases, the distinction between for example metadata and annotation is often vague. It's not up to STAM to make strict choices in disambiguating that, that's up to whatever model the user is modeling using STAM. 

In STAM we follow the simple premise "everything is an annotation", so basically every piece of data that a user associates with anything is an annotation. I think that helps reduce complexity overall. The use of different selectors results in essentially different types of annotation. You could say that an Annotation with a DatasetSelector is 'vocabulary metadata', or describing the internal model as you call it (still, it's external to STAM in the sense that it's not something STAM defines). Likewise, annotation with a ResourceSelector could be called 'resource metadata' or 'resource annotation', here the line between metadata/annotation already comes blurrier. It can be used for associating for instance the title of a resource (=metadata), but also some kind of automatically produced classification on a document as a whole (which you may already be more inclined to call annotation rather than metadata). 

> Unless @proycon really wants to do the Gödel trick: represent STAM as a STAM dataset. But I think that is an academic exercise.

No :) I think that goes even one step further than @eduarddrenth  meant and I certainly don't want to go there indeed.
