### ISSUE TITLE
How to deal with resource changes?

### ISSUE THREAD

**Issue by eduarddrenth** [annotation/stam#5]
Perhaps think about support for dealing with resource changes that possibly break existing Cursors.

- timestamp?
- checksum?
- notification via pub/sub (resource notifies stam)?
- stam stores initially selected text and validates if that changed?
- rely on persistent identifiers?
- ....

**Comment by proycon** [comment]
Yes, that's an important point. I in fact already gave it some thought an formulated a STAM extension for text validation here:  https://github.com/annotation/stam/tree/master/extensions/stam-textvalidation (also linked from the main document, but you might have missed it in the torrent of info). It implements precisely two of the things which you suggested above.

Such things would be implemented as extensions on of the STAM model, as we want to keep the core model as light as possible. Implementations would explicitly state what extensions they support.

**Comment by eduarddrenth** [comment]
I understand keeping the core light, but perhaps the importance of this issue justifies incorporating resource validation in the core

**Comment by proycon** [comment]
I agree it's important yes; it probably will be one of the extensions that will be implemented first and recommended widely. Being an extension doesn't necessarily mean it has to be in another code base, we're just trying to formulate things with an eye on modularity and maintainability (and keeping the parts as simple as we can).

**Comment by dirkroorda** [comment]
FYI: in Text-Fabric I left source validation out, but it should be part of the toolkit. Especially when people annotate specific versions of an existing resource, there should be checks that when they create those annotations, they have indeed checked out that resource in that version.

I hope to add it in Text-Fabric once, and there it will be in the core machinery, because in Text-Fabric I have a different concept of modularity.

When the ecosystem around  corpus is still small, you can do without the validation. As soon as it grows, you need it.
